spring:
  application:
    name: api-gateway

server:
  port: 3100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

zuul:
  routes:
    test:
      path: /test/**
      serviceId: eureka-consumer-ribbon